---

language: "python"

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

install:
  - "~/virtualenv/python3.6/bin/pip install pip setuptools -U"
  - "~/virtualenv/python3.6/bin/pip install tox"

script:
  - "tox"
